version: "3.8"
services:
  ambassador-db:
    container_name: ambassador-db
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=ambassador_db
      - MYSQL_USER=ambas
      - MYSQL_PASSWORD=ampass3210
      - MYSQL_ROOT_PASSWORD=rootampass3210
    ports:
      - "3306:3306"
    networks:
      - ambassador_net
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql

  ambassador-phpmyadmin:
    depends_on:
      - ambassador-db
    container_name: ambassador-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      - PMA_HOST=ambassador-db
    ports:
      - "8011:80"
    networks:
      - ambassador_net
    restart: always

  ambassador-redis:
    container_name: ambassador-redis
    image: redis:7.2
    ports:
      - 6379:6379
    networks:
      - ambassador_net
    restart: always

  ambassador-mailhog:
    container_name: ambassador-mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ambassador_net
    restart: always

  ambassador-kafka:
    container_name: ambassador-kafka
    image: bitnami/kafka:3.5.1
    restart: always
    ports:
      - 9092:9092
    networks:
      - ambassador_net
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@0.0.0.0:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./data/kafka:/bitnami/kafka

networks:
  ambassador_net:
    name: ambassador_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1